# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jlog < Formula
  desc "Pretty-print JSON logs"
  homepage "https://github.com/jrockway/json-logs"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.6/jlog_v0.0.6_darwin_arm64"
      sha256 "da95426f786a57efca2fbd08d643a4fcd24219b1de1ce357ed4e199417463fe4"

      def install
        bin.install "jlog_v0.0.6_darwin_arm64" => "jlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.6/jlog_v0.0.6_darwin_amd64"
      sha256 "f1d9cbec62fb8466cb97eff78624c908575ae7f96c0b202f701d116fc68cb663"

      def install
        bin.install "jlog_v0.0.6_darwin_amd64" => "jlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.6/jlog_v0.0.6_linux_arm64"
      sha256 "af546c115eff4b27d468cb856c8f8023d79ff74f6767be4fb1acce1c874f38e7"

      def install
        bin.install "jlog_v0.0.6_linux_arm64" => "jlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.6/jlog_v0.0.6_linux_amd64"
      sha256 "28f2d0c62eaf632310c8e9f00277d9c84c210feb9d4b96c8181537b59d878cd8"

      def install
        bin.install "jlog_v0.0.6_linux_amd64" => "jlog"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.6/jlog_v0.0.6_linux_armv6"
      sha256 "26043c9bc09a9c67cf548993562c837f1c70e4aca04154f7bc8c244468bf6069"

      def install
        bin.install "jlog_v0.0.6_linux_armv6" => "jlog"
      end
    end
  end

  conflicts_with "jlog"

  test do
    system "#{bin}/jlog --version"
  end
end
