# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jlog < Formula
  desc "Pretty-print JSON logs"
  homepage "https://github.com/jrockway/json-logs"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.8/jlog_v0.0.8_darwin_amd64"
      sha256 "e8c8de01ad16c29945a9cbe5209549fb44648f7b5aaca172d0c6903b509d4f19"

      def install
        bin.install "jlog_v0.0.8_darwin_amd64" => "jlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.8/jlog_v0.0.8_darwin_arm64"
      sha256 "f2d5c6d1214e609d80e9f070bf41b4222a56a9f2bef690a2b98b512832bd427a"

      def install
        bin.install "jlog_v0.0.8_darwin_arm64" => "jlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.8/jlog_v0.0.8_linux_arm64"
      sha256 "a90327a5380f726f84bd4799bd963acd3e2bd467d2254de1ee0578b3a2374ff4"

      def install
        bin.install "jlog_v0.0.8_linux_arm64" => "jlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.8/jlog_v0.0.8_linux_amd64"
      sha256 "df9db621f8649119a76cd6d7fb7c2c8da9f831d4411b23879dfd60336dd93d82"

      def install
        bin.install "jlog_v0.0.8_linux_amd64" => "jlog"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jrockway/json-logs/releases/download/v0.0.8/jlog_v0.0.8_linux_armv6"
      sha256 "a9ee0a7fb3ff44aae529cfc49c547b12bc599564ddca4ef6ea17efd2ec8cd642"

      def install
        bin.install "jlog_v0.0.8_linux_armv6" => "jlog"
      end
    end
  end

  conflicts_with "jlog"

  test do
    system "#{bin}/jlog --version"
  end
end
