# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlJq < Formula
  desc "Query Kubernetes objects with JQ"
  homepage "https://github.com/jrockway/kubectl-jq"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrockway/kubectl-jq/releases/download/v0.0.2/kubectl-jq_v0.0.2_darwin_amd64"
      sha256 "2eed025be3016e35000bc2c3405a4c880adef8629b3001e4630c2f78c4106385"

      def install
        bin.install "kubectl-jq_v0.0.2_darwin_amd64" => "kubectl-jq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrockway/kubectl-jq/releases/download/v0.0.2/kubectl-jq_v0.0.2_darwin_arm64"
      sha256 "f1fc5f76980c0b4f610eb20636bd2b5da19e34f0a5ed15b63076c66e47f6589e"

      def install
        bin.install "kubectl-jq_v0.0.2_darwin_arm64" => "kubectl-jq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jrockway/kubectl-jq/releases/download/v0.0.2/kubectl-jq_v0.0.2_linux_armv6"
      sha256 "d9e2a50ba8ada7c315a8d0ec429d4ac3e3a055647ffb6fd0f20e5abb4a9993a3"

      def install
        bin.install "kubectl-jq_v0.0.2_linux_armv6" => "kubectl-jq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrockway/kubectl-jq/releases/download/v0.0.2/kubectl-jq_v0.0.2_linux_amd64"
      sha256 "2926159f9a18126c7278f294ac48f0e103af34f6d49e6578144b34f03c257ea4"

      def install
        bin.install "kubectl-jq_v0.0.2_linux_amd64" => "kubectl-jq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jrockway/kubectl-jq/releases/download/v0.0.2/kubectl-jq_v0.0.2_linux_arm64"
      sha256 "9fb47198a4920494fd121cfc228bb69eb99bf42ff1ae8c808ddddef2b1e40977"

      def install
        bin.install "kubectl-jq_v0.0.2_linux_arm64" => "kubectl-jq"
      end
    end
  end

  test do
    system "#{bin}/kubectl-jq --help"
  end
end
